/* This file is auto-generated by Payload */
import config from '@/payload.config'
import { RootPage } from '@payloadcms/next/views'
import { importMap } from '@/app/(payload)/admin/importMap'

type Args = {
  params: Promise<{
    segments: string[]
  }>
  searchParams: Promise<{
    [key: string]: string | string[]
  }>
}

export default function Page({ params, searchParams }: Args) {
  return RootPage({ config, params, searchParams, importMap })
}
